# 첫 번째 방법
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 20
ORDER BY HOUR;

# 두 번째 방법
# SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
# FROM ANIMAL_OUTS
# WHERE HOUR(DATETIME) BETWEEN 9 AND 20
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR;