-- 첫 번째 방법
SELECT MIN(DATETIME) AS 시간
FROM ANIMAL_INS;

-- 두 번째 방법
SELECT DATETIME AS 시간 
FROM ANIMAL_INS 
WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS);

-- 세 번째 방법
SELECT DATETIME AS 시간
FROM ANIMAL_INS
ORDER BY 1 ASC
LIMIT 0,1;