with recursive time as (
    SELECT 0 AS H
    UNION ALL 
    SELECT H+1 
    FROM time 
    WHERE H < 23
)
SELECT T.H AS HOUR, COUNT(A.DATETIME) AS COUNT
FROM ANIMAL_OUTS A 
RIGHT OUTER JOIN time T ON(HOUR(A.DATETIME) = T.H)
GROUP BY HOUR
HAVING HOUR BETWEEN 0 AND 24
ORDER BY HOUR;